//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEERJACore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppa_entities : DbContext
    {
        public ppa_entities()
            : base("name=ppa_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<neerja_evaluation_form> neerja_evaluation_form { get; set; }
        public virtual DbSet<neerja_evaluation_form_score> neerja_evaluation_form_score { get; set; }
        public virtual DbSet<neerja_evaluation_item> neerja_evaluation_item { get; set; }
        public virtual DbSet<neerja_preflight_check_form> neerja_preflight_check_form { get; set; }
        public virtual DbSet<neerja_preflight_check_form_sign> neerja_preflight_check_form_sign { get; set; }
        public virtual DbSet<neerja_preflight_check_item> neerja_preflight_check_item { get; set; }
        public virtual DbSet<neerja_preflight_check_item_category> neerja_preflight_check_item_category { get; set; }
        public virtual DbSet<neerja_preflight_ckeck_form_item> neerja_preflight_ckeck_form_item { get; set; }
        public virtual DbSet<neerja_preflight_from_remark> neerja_preflight_from_remark { get; set; }
        public virtual DbSet<view_neerja_pfc_item> view_neerja_pfc_item { get; set; }
        public virtual DbSet<view_neerja_scc_report> view_neerja_scc_report { get; set; }
        public virtual DbSet<neerja_scc_report_form> neerja_scc_report_form { get; set; }
    }
}
