//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEERJACore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_neerja_pfc_item
    {
        public Nullable<int> category_order_id { get; set; }
        public string item_title { get; set; }
        public int item_id { get; set; }
        public string category { get; set; }
        public Nullable<int> category_id { get; set; }
        public int flight_id { get; set; }
        public int crew_id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public Nullable<int> group_id { get; set; }
        public string job_group { get; set; }
        public string nid { get; set; }
        public Nullable<int> position_id { get; set; }
        public string position { get; set; }
        public Nullable<bool> is_servicable { get; set; }
        public string remark { get; set; }
        public Nullable<int> result_id { get; set; }
    }
}
