//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEERJACore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_neerja_scc_report
    {
        public int id { get; set; }
        public int flight_id { get; set; }
        public Nullable<int> crew_id { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_sign { get; set; }
        public string crew_no { get; set; }
        public string catering_issue { get; set; }
        public string airport_service { get; set; }
        public string technical { get; set; }
        public string safety_issue { get; set; }
        public string general_issue { get; set; }
        public string remark { get; set; }
        public string position { get; set; }
    }
}
