using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class ViewEFBDSPRelease
    {
        /*public int Id { get; set; }
        public int? FlightId { get; set; }
        public bool? ActualWXDSP { get; set; }
        public bool? ActualWXCPT { get; set; }
        public string ActualWXDSPRemark { get; set; }
        public string ActualWXCPTRemark { get; set; }
        public bool? WXForcastDSP { get; set; }
        public bool? WXForcastCPT { get; set; }
        public string WXForcastDSPRemark { get; set; }
        public string WXForcastCPTRemark { get; set; }
        public bool? SigxWXDSP { get; set; }
        public bool? SigxWXCPT { get; set; }
        public string SigxWXDSPRemark { get; set; }
        public string SigxWXCPTRemark { get; set; }
        public bool? WindChartDSP { get; set; }
        public bool? WindChartCPT { get; set; }
        public string WindChartDSPRemark { get; set; }
        public string WindChartCPTRemark { get; set; }
        public bool? NotamDSP { get; set; }
        public bool? NotamCPT { get; set; }
        public string NotamDSPRemark { get; set; }
        public string NotamCPTRemark { get; set; }
        public bool? ComputedFligthPlanDSP { get; set; }
        public bool? ComputedFligthPlanCPT { get; set; }
        public string ComputedFligthPlanDSPRemark { get; set; }
        public string ComputedFligthPlanCPTRemark { get; set; }
        public bool? ATCFlightPlanDSP { get; set; }
        public bool? ATCFlightPlanCPT { get; set; }
        public string ATCFlightPlanDSPRemark { get; set; }
        public string ATCFlightPlanCPTRemark { get; set; }
        public bool? PermissionsDSP { get; set; }
        public bool? PermissionsCPT { get; set; }
        public string PermissionsDSPRemark { get; set; }
        public string PermissionsCPTRemark { get; set; }
        public bool? JeppesenAirwayManualDSP { get; set; }
        public bool? JeppesenAirwayManualCPT { get; set; }
        public string JeppesenAirwayManualDSPRemark { get; set; }
        public string JeppesenAirwayManualCPTRemark { get; set; }
        public bool? MinFuelRequiredDSP { get; set; }
        public bool? MinFuelRequiredCPT { get; set; }
        public decimal? MinFuelRequiredPilotReq { get; set; }
        public bool? GeneralDeclarationDSP { get; set; }
        public bool? GeneralDeclarationCPT { get; set; }
        public string GeneralDeclarationDSPRemark { get; set; }
        public string GeneralDeclarationCPTRemark { get; set; }
        public bool? FlightReportDSP { get; set; }
        public bool? FlightReportCPT { get; set; }
        public string FlightReportDSPRemark { get; set; }
        public string FlightReportCPTRemark { get; set; }
        public bool? TOLndCardsDSP { get; set; }
        public bool? TOLndCardsCPT { get; set; }
        public string TOLndCardsDSPRemark { get; set; }
        public string TOLndCardsCPTRemark { get; set; }
        public bool? LoadSheetDSP { get; set; }
        public bool? LoadSheetCPT { get; set; }
        public string LoadSheetDSPRemark { get; set; }
        public string LoadSheetCPTRemark { get; set; }
        public bool? FlightSafetyReportDSP { get; set; }
        public bool? FlightSafetyReportCPT { get; set; }
        public string FlightSafetyReportDSPRemark { get; set; }
        public string FlightSafetyReportCPTRemark { get; set; }
        public bool? AVSECIncidentReportDSP { get; set; }
        public bool? AVSECIncidentReportCPT { get; set; }
        public string AVSECIncidentReportDSPRemark { get; set; }
        public string AVSECIncidentReportCPTRemark { get; set; }
        public bool? OperationEngineeringDSP { get; set; }
        public bool? OperationEngineeringCPT { get; set; }
        public string OperationEngineeringDSPRemark { get; set; }
        public string OperationEngineeringCPTRemark { get; set; }
        public bool? VoyageReportDSP { get; set; }
        public bool? VoyageReportCPT { get; set; }
        public string VoyageReportDSPRemark { get; set; }
        public string VoyageReportCPTRemark { get; set; }
        public bool? PIFDSP { get; set; }
        public bool? PIFCPT { get; set; }
        public string PIFDSPRemark { get; set; }
        public string PIFCPTRemark { get; set; }
        public bool? GoodDeclarationDSP { get; set; }
        public bool? GoodDeclarationCPT { get; set; }
        public string GoodDeclarationDSPRemark { get; set; }
        public string GoodDeclarationCPTRemark { get; set; }
        public bool? IPADDSP { get; set; }
        public bool? IPADCPT { get; set; }
        public string IPADDSPRemark { get; set; }
        public string IPADCPTRemark { get; set; }
        public DateTime? DateConfirmed { get; set; }
        public int? DispatcherId { get; set; }
        public string DSPName { get; set; }
        public string DSPPID { get; set; }
        public string DSPNID { get; set; }
        public string DSPMobile { get; set; }
        public string JLSignedBy { get; set; }
        public DateTime? JLDatePICApproved { get; set; }
        public int? PICId { get; set; }
        public string PIC { get; set; }
        public int? OFPTOTALFUEL { get; set; }
        public Nullable<bool> OperationalFlightPlanFOO { get; set; }
        public Nullable<bool> OperationalFlightPlanCMDR { get; set; }
        public string OperationalFlightPlanFOORemark { get; set; }
        public string OperationalFlightPlanCMDRRemark { get; set; }
        */
        public Nullable<int> Id { get; set; }
        public int FlightId { get; set; }
        public Nullable<bool> ActualWXDSP { get; set; }
        public Nullable<bool> ActualWXCPT { get; set; }
        public string ActualWXDSPRemark { get; set; }
        public string ActualWXCPTRemark { get; set; }
        public Nullable<bool> WXForcastDSP { get; set; }
        public Nullable<bool> WXForcastCPT { get; set; }
        public string WXForcastDSPRemark { get; set; }
        public string WXForcastCPTRemark { get; set; }
        public Nullable<bool> SigxWXDSP { get; set; }
        public Nullable<bool> SigxWXCPT { get; set; }
        public string SigxWXDSPRemark { get; set; }
        public string SigxWXCPTRemark { get; set; }
        public Nullable<bool> WindChartDSP { get; set; }
        public Nullable<bool> WindChartCPT { get; set; }
        public string WindChartDSPRemark { get; set; }
        public string WindChartCPTRemark { get; set; }
        public Nullable<bool> NotamDSP { get; set; }
        public Nullable<bool> NotamCPT { get; set; }
        public string NotamDSPRemark { get; set; }
        public string NotamCPTRemark { get; set; }
        public Nullable<bool> ComputedFligthPlanDSP { get; set; }
        public Nullable<bool> ComputedFligthPlanCPT { get; set; }
        public string ComputedFligthPlanDSPRemark { get; set; }
        public string ComputedFligthPlanCPTRemark { get; set; }
        public Nullable<bool> ATCFlightPlanDSP { get; set; }
        public Nullable<bool> ATCFlightPlanCPT { get; set; }
        public string ATCFlightPlanDSPRemark { get; set; }
        public string ATCFlightPlanCPTRemark { get; set; }
        public Nullable<bool> PermissionsDSP { get; set; }
        public Nullable<bool> PermissionsCPT { get; set; }
        public string PermissionsDSPRemark { get; set; }
        public string PermissionsCPTRemark { get; set; }
        public Nullable<bool> JeppesenAirwayManualDSP { get; set; }
        public Nullable<bool> JeppesenAirwayManualCPT { get; set; }
        public string JeppesenAirwayManualDSPRemark { get; set; }
        public string JeppesenAirwayManualCPTRemark { get; set; }
        public Nullable<bool> MinFuelRequiredDSP { get; set; }
        public Nullable<bool> MinFuelRequiredCPT { get; set; }
        public Nullable<decimal> MinFuelRequiredPilotReq { get; set; }
        public Nullable<bool> GeneralDeclarationDSP { get; set; }
        public Nullable<bool> GeneralDeclarationCPT { get; set; }
        public string GeneralDeclarationDSPRemark { get; set; }
        public string GeneralDeclarationCPTRemark { get; set; }
        public Nullable<bool> FlightReportDSP { get; set; }
        public Nullable<bool> FlightReportCPT { get; set; }
        public string FlightReportDSPRemark { get; set; }
        public string FlightReportCPTRemark { get; set; }
        public Nullable<bool> TOLndCardsDSP { get; set; }
        public Nullable<bool> TOLndCardsCPT { get; set; }
        public string TOLndCardsDSPRemark { get; set; }
        public string TOLndCardsCPTRemark { get; set; }
        public Nullable<bool> LoadSheetDSP { get; set; }
        public Nullable<bool> LoadSheetCPT { get; set; }
        public string LoadSheetDSPRemark { get; set; }
        public string LoadSheetCPTRemark { get; set; }
        public Nullable<bool> FlightSafetyReportDSP { get; set; }
        public Nullable<bool> FlightSafetyReportCPT { get; set; }
        public string FlightSafetyReportDSPRemark { get; set; }
        public string FlightSafetyReportCPTRemark { get; set; }
        public Nullable<bool> AVSECIncidentReportDSP { get; set; }
        public Nullable<bool> AVSECIncidentReportCPT { get; set; }
        public string AVSECIncidentReportDSPRemark { get; set; }
        public string AVSECIncidentReportCPTRemark { get; set; }
        public Nullable<bool> OperationEngineeringDSP { get; set; }
        public Nullable<bool> OperationEngineeringCPT { get; set; }
        public string OperationEngineeringDSPRemark { get; set; }
        public string OperationEngineeringCPTRemark { get; set; }
        public Nullable<bool> VoyageReportDSP { get; set; }
        public Nullable<bool> VoyageReportCPT { get; set; }
        public string VoyageReportDSPRemark { get; set; }
        public string VoyageReportCPTRemark { get; set; }
        public Nullable<bool> PIFDSP { get; set; }
        public Nullable<bool> PIFCPT { get; set; }
        public string PIFDSPRemark { get; set; }
        public string PIFCPTRemark { get; set; }
        public Nullable<bool> GoodDeclarationDSP { get; set; }
        public Nullable<bool> GoodDeclarationCPT { get; set; }
        public string GoodDeclarationDSPRemark { get; set; }
        public string GoodDeclarationCPTRemark { get; set; }
        public Nullable<bool> IPADDSP { get; set; }
        public Nullable<bool> IPADCPT { get; set; }
        public string IPADDSPRemark { get; set; }
        public string IPADCPTRemark { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<int> DispatcherId { get; set; }
        public string DSPName { get; set; }
        public string DSPPID { get; set; }
        public string DSPNID { get; set; }
        public string DSPMobile { get; set; }
        public string JLSignedBy { get; set; }
        public Nullable<System.DateTime> JLDatePICApproved { get; set; }
        public Nullable<int> PICId { get; set; }
        public string PIC { get; set; }
        public Nullable<bool> OperationalFlightPlanFOO { get; set; }
        public Nullable<bool> OperationalFlightPlanCMDR { get; set; }
        public string OperationalFlightPlanFOORemark { get; set; }
        public string OperationalFlightPlanCMDRRemark { get; set; }
        public Nullable<bool> ATSFlightPlanFOO { get; set; }
        public Nullable<bool> ATSFlightPlanCMDR { get; set; }
        public string ATSFlightPlanFOORemark { get; set; }
        public string ATSFlightPlanCMDRRemark { get; set; }
        public Nullable<bool> VldEFBFOO { get; set; }
        public Nullable<bool> VldEFBCMDR { get; set; }
        public string VldEFBFOORemark { get; set; }
        public string VldEFBCMDRRemark { get; set; }
        public Nullable<bool> VldFlightCrewFOO { get; set; }
        public Nullable<bool> VldFlightCrewCMDR { get; set; }
        public string VldFlightCrewFOORemark { get; set; }
        public string VldFlightCrewCMDRRemark { get; set; }
        public Nullable<bool> VldMedicalFOO { get; set; }
        public Nullable<bool> VldMedicalCMDR { get; set; }
        public string VldMedicalFOORemark { get; set; }
        public string VldMedicalCMDRRemark { get; set; }
        public Nullable<bool> VldPassportFOO { get; set; }
        public Nullable<bool> VldPassportCMDR { get; set; }
        public string VldPassportFOORemark { get; set; }
        public string VldPassportCMDRRemark { get; set; }
        public Nullable<bool> VldCMCFOO { get; set; }
        public Nullable<bool> VldCMCCMDR { get; set; }
        public string VldCMCFOORemark { get; set; }
        public string VldCMCCMDRRemark { get; set; }
        public Nullable<bool> VldRampPassFOO { get; set; }
        public Nullable<bool> VldRampPassCMDR { get; set; }
        public string VldRampPassFOORemark { get; set; }
        public string VldRampPassCMDRRemark { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> MinFuelRequiredCFP { get; set; }
        public Nullable<int> OFPTOTALFUEL { get; set; }
    }
}
